In [1]:
import numpy as np

# a. Struktur Data

## 1. Lists

## 1.1 List

In [134]:
aList = ["Kevin", 20, "Jakarta", True]

In [135]:
aList

['Kevin', 20, 'Jakarta', True]

In [136]:
type(aList)

list

## 2. Tuples

In [137]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']

In [53]:
bin_colors = ('Red', 'Green', 'Blue', 'Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [54]:
print(f"The elements after third element omwards are {bin_colors[2:]}")

The elements after third element omwards are ('Blue', 'Yellow')


In [55]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


## 3. Dictionary

In [138]:
bin_language ={
    "native_language": "Jawa",
    "approved_language": "Bahasa",
    "refused_language": "Spanish"
}

In [139]:
print(bin_language)

{'native_language': 'Jawa', 'approved_language': 'Bahasa', 'refused_language': 'Spanish'}


In [142]:
bin_language.get('approved_language')

'Bahasa'

In [143]:
bin_language['approved_language']

'Bahasa'

In [144]:
bin_language['approved_language']='English'

In [145]:
print(bin_language)

{'native_language': 'Jawa', 'approved_language': 'English', 'refused_language': 'Spanish'}


## 4. Sets

## 1.1 Set

In [33]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [36]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [37]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'blood', 'fire hydrant', 'rose', 'leaves', 'dandelions'}


In [38]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'fire hydrant', 'leaves'}


## 5. Data Frames

## 1.1 DataFrame

In [146]:
import pandas as pd
df = pd.DataFrame([
    ['a', 'Kevin', 20, True],
    ['b', 'Ucup', 34, False],
    ['c', 'Otong', 54, True],
    ['d', 'Ujang', 17, False]])
df.columns = ['ID', 'Name', 'Age', 'Decision']
print(df)

  ID   Name  Age  Decision
0  a  Kevin   20      True
1  b   Ucup   34     False
2  c  Otong   54      True
3  d  Ujang   17     False


## 1.2 Column Selection

In [147]:
df[['Name', 'Age']]

Name  Age
0  Kevin   20
1   Ucup   34
2  Otong   54
3  Ujang   17

In [148]:
df.iloc[:,3]

0     True
1    False
2     True
3    False
Name: Decision, dtype: bool

## 1.3 Row Selection

In [149]:
df.iloc[1:3,:]

ID   Name  Age  Decision
1  b   Ucup   34     False
2  c  Otong   54      True

In [150]:
df[df.Age>30]

ID   Name  Age  Decision
1  b   Ucup   34     False
2  c  Otong   54      True

In [151]:
df[df.Age<30]

ID   Name  Age  Decision
0  a  Kevin   20      True
3  d  Ujang   17     False

In [153]:
df[df.Age>=20]

ID   Name  Age  Decision
0  a  Kevin   20      True
1  b   Ucup   34     False
2  c  Otong   54      True

## 6. Matrix

## 1.1 Matrix

In [57]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [58]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [59]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [60]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# b. Tipe Data Abstrak

## 1. Vector

In [61]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [62]:
print(type(myVector))

<class 'list'>


In [63]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [64]:
print(type(myVector))

<class 'numpy.ndarray'>


## 2. Stack

In [171]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self,item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [172]:
stack=Stack()
stack.push('Java')
stack.push('Python')
stack.push('Ruby')
stack.push('PHP')

### Pop

In [173]:
stack.pop()

'PHP'

In [174]:
stack.isEmpty()

False

In [175]:
languages = ['Java']

In [176]:
languages.append('Python')
languages.append('Ruby')
languages.append('PHP')

In [177]:
languages

['Java', 'Python', 'Ruby', 'PHP']

#### Penggunaan 'append' hanya berlaku untuk penggunaan struktur List. [] Menandakan isi statement tersebut adalah list

In [178]:
print(type(languages))

<class 'list'>


## 3. Queue

In [195]:
class Queue:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self,item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [196]:
queue = Queue()

In [197]:
queue.enqueue("Red")

In [198]:
queue.enqueue('Green')

In [199]:
queue.enqueue('Blue')

In [200]:
queue.enqueue('Yellow')

In [201]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [203]:
print(queue.dequeue())

Red


#### Queue membuat statement menjadi fungsi antrian, dimana jika queue pertama sudah di output, maka yang akan di print selanjutnya adalah queue kedua

In [204]:
print(queue.dequeue())

Green
